apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: helloworld
  namespace: argocd
spec:
  description: Application de démonstration du pattern CI/CD complet
  sourceRepos:
  - http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/infra/helloworld-iac.git
  destinations:
  - server: https://kubernetes.default.svc
    namespace: helloworld-dev
  - server: https://kubernetes.default.svc
    namespace: helloworld-rec
  - server: https://kubernetes.default.svc
    namespace: helloworld-preprod
  - server: https://kubernetes.default.svc
    namespace: helloworld
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
