apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-gitlab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Doit syncer après tf-controller (CRDs Terraform disponibles)
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/skip-reconcile: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/poc-devops-elkouhen/platform-gitops
    targetRevision: main
    path: argocd/platform/tf-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: flux-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
