apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: helloworld-dev
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:ABjvsPABb6aFWTGQWNnQVUSHFKD23iJ9vqBK9gEGlOrXGabEc6JZNdaoCTqITz2BFhBb8+G2rfEQr9zo7nodp2I2WFbV6RsTfyL5YYzH8fS8+nAjZDprSbg5+tTCqgCSKIY9EOe+CDBZ2nzmgFKuvYA=,iv:YEHRonvhWc6vnpwYSa8axTo8ILSD4dkuPoczHfDs9Dw=,tag:hyO9iyRLUIdjzebVt1pCdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMmxISEluT3YzRTFZL1VB
            WkpEcmk4OFVDb3JiQ1pDT0JGQmhHb2o5b1NJClB0QW1WQThGZ21XdmZ6NUFCRFcx
            MUhUZjgrQ1NYVHk1WHpNWW01VmxmaE0KLS0tIHVjWnFqbDVMMlpEdEoxa05rV1Z3
            cHc1RlZ4N3gycDBMVmlDR2lUU25ybWsKh+7QOvleR4qIkFxrqxXzJE6S2iebm2ys
            PM8RP1d+SCE6lTemDaOZD9eC3nNX2YkPXuOPMm3h1YUjGEIMAJeq8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age136dut7ljt7angdg84vpdldfqqgd4hv64la7afc80z0c67k68nq8s2sj6yz
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-07-01T15:10:21Z"
    mac: ENC[AES256_GCM,data:Vy6fdK9sKxJcKIaDE7i1jOLjGxKtM9sCDQXtn6oqjHlDCQROnxbTmDlmUoPuOHyoz7HR8ghlpcCMte0ZR5WhNUvQiDtJE1dRypnZJnrazQiWekp7GONuWxJdssYc8bP4xSm6yFHxH+JDmAqiG6S4NZfs2TvOKe6HN1Js1sr+i+M=,iv:pjIL448VgGSxZUaSAo+SIEDX08xqKqDwKPQZxyicvWw=,tag:bhRn1Z6nm3H0WUHIuRfHaw==,type:str]
    version: 3.13.2
