apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitlab-projects-iac
  namespace: flux-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  interval: 1m
  url: https://github.com/k8s-gitops-lab/gitlab-projects-iac.git
  ref:
    branch: main
  secretRef:
    # Secret géré par SOPS dans flux-secrets/github-credentials.yaml.
    name: github-credentials
