apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zscaler-ca-configmap.yaml
  - platform-gitops-source.yaml
  - flux-secrets-kustomization.yaml
  - tf-credentials-job.yaml
  - terraform-runner-rbac.yaml
  - cluster-admin-binding.yaml
  - gitlab-repo.yaml
  - terraform-gitlab.yaml
