name: helloworld
hasPreprod: true
services:
  - helloworld-svc
  - helloworld-gui
manifests:
  path: k8s
  projectPath: infra/helloworld-iac
  sourceURL: 'https://gitlab.192.168.33.100.nip.io/infra/helloworld-iac'
code:
  projectPath: infra/helloworld
  sourceURL: 'https://gitlab.192.168.33.100.nip.io/infra/helloworld'
