name: helloworld
hasPreprod: true
services:
  - helloworld-svc
  - helloworld-gui
manifests:
  path: k8s
  sourceURL: 'https://gitlab.192.168.33.100.nip.io/root/helloworld-iac'
code:
  sourceURL: 'https://gitlab.192.168.33.100.nip.io/root/helloworld'
