apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.192.168.33.100.nip.io
  dex.config: |
    connectors:
      - type: gitlab
        id: gitlab
        name: GitLab
        config:
          baseURL: https://gitlab.192.168.33.100.nip.io
          clientID: $dex.gitlab.clientID
          clientSecret: $dex.gitlab.clientSecret
          redirectURI: https://argocd.192.168.33.100.nip.io/api/dex/callback
